### ISSUE TITLE
Add bluetooth support for the old protocol

### ISSUE THREAD

**Issue by oguzatagan** [syssi/esphome-ant-bms#61]
Hi
i have a 2019 version ant bms. İ try install your code in my esp32. But no connection. İ attach log.
[logs_powerwall-bms_run.txt](https://github.com/syssi/esphome-ant-bms/files/11223707/logs_powerwall-bms_run.txt)

my code 
```
substitutions:
  name: powerwall-bms
  device_description: "Monitor and control a ANT Battery Management System (ANT-BMS) via BLE"
  external_components_source: github://syssi/esphome-ant-bms@main
  mac_address: aa:bb:cc:92:23:45

esphome:
  name: powerwall-bms
  platform: ESP32
  board: esp32dev
  platformio_options: 
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L
  project:
    name: "syssi.esphome-ant-bms"
    version: 2.0.0

external_components:
  - source: ${external_components_source}
    refresh: 5s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: 

logger:

# If you use Home Assistant please remove this `mqtt` section and uncomment the native `api` component!
api:
  encryption:
    key: 

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("ANT-", 0) == 0) {
            ESP_LOGI("ble_adv", "New ANT-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }
ble_client:
  - id: client0
    mac_address: ${mac_address}

ant_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 5s

binary_sensor:
  - platform: ant_bms_ble
    ant_bms_ble_id: bms0
    online_status:
      name: "${name} online status"

sensor:
  - platform: ant_bms_ble
    ant_bms_ble_id: bms0
    battery_strings:
      name: "${name} battery strings"
    current:
      name: "${name} current"
    soc:
      name: "${name} soc"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    capacity_remaining:
      name: "${name} capacity remaining"
    battery_cycle_capacity:
      name: "${name} battery cycle capacity"
    total_voltage:
      name: "${name} total voltage"
    total_runtime:
      name: "${name} total runtime"
    average_cell_voltage:
      name: "${name} average cell voltage"
    power:
      name: "${name} power"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    temperature_5:
      name: "${name} temperature 5"
    temperature_6:
      name: "${name} temperature 6"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    charge_mosfet_status_code:
      name: "${name} charge mosfet status code"
    discharge_mosfet_status_code:
      name: "${name} discharge mosfet status code"
    balancer_status_code:
      name: "${name} balancer status code"

text_sensor:
  - platform: ant_bms_ble
    ant_bms_ble_id: bms0
    charge_mosfet_status:
      name: "${name} charge mosfet status"
    discharge_mosfet_status:
      name: "${name} discharge mosfet status"
    balancer_status:
      name: "${name} balancer status"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
    device_model:
      name: "${name} device model"
    software_version:
      name: "${name} software version"

switch:
  - platform: ant_bms_ble
    ant_bms_ble_id: bms0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"
    buzzer:
      name: "${name} buzzer"

button:
  - platform: ant_bms_ble
    ant_bms_ble_id: bms0
    shutdown:
      name: "${name} shutdown"
    clear_system_log:
      name: "${name} clear system log"
    factory_reset:
      name: "${name} factory reset"
    restart:
      name: "${name} restart"
```

**Comment by syssi** [comment]
Could you tell me the exact Android app you are using to talk to the BMS?

**Comment by syssi** [comment]
Did you change the default password of the BMS?

**Comment by oguzatagan** [comment]
Hello again. As far as I can see now, bms is broadcasting 2 broadcasts. They are BMS-ANT24C mac adress aa:bb:cc:91:23:45 and ANT-BLE24C mac is aa:bb:cc:92:23:45. i paired  first one 1234 password. i didnt connect second one with my app. New app didnt work. But i have a second app this is vbms android app. I wanted to add these details, maybe to help with the solution.

**Comment by syssi** [comment]
Your BMS supports the old ANT-BMS protocol because the old App is required and the default password is `1234` instead of `12345678` but it looks like the bluetooth module of your BMS supports BLE and Bluetooth Rfcomm (serial connection via bluetooth). The Android app uses the serial connection via bluetooth approach to talk to the BMS. Rfcomm isn't supported by ESPHome.

I would like to try to talk to your BMS using a BLE client connection. If we are lucky the BMS will respond to the status request of the old protocol via BLE too. I've prepared a feature branch already. Please change your YAML from:

```
substitutions:
  name: ant-bms-ble
  external_components_source: github://syssi/esphome-ant-bms@main
```

to

```
substitutions:
  name: ant-bms-ble
  external_components_source: github://syssi/esphome-ant-bms@old-proto-ble
```

and compile + flash your ESP32. Please provide another log capture. In best case we will see some RAW traffic if the BLE connection is established. Please use this MAC address again:

```
[18:15:20][I][ble_adv:050]:   Name: ANT-BLE24C
[18:15:20][I][ble_adv:051]:   MAC address: AA:BB:CC:92:23:45
[18:15:20][D][ble_adv:052]:   Advertised service UUIDs:
[18:15:20][D][ble_adv:054]:     - 0xFFE0
[18:15:20][D][ble_adv:054]:     - 0xFEE7
```

**Comment by oguzatagan** [comment]
here is the log. Bms connected but no comminication sir.
[logs.txt](https://github.com/syssi/esphome-ant-bms/files/11232451/logs.txt)

**Comment by syssi** [comment]
Could you increase the log level by adding the follow lines to your YAML and try again?

```
logger:
  level: VERY_VERBOSE
  logs:
    ant_bms_ble: VERY_VERBOSE
    ble_client: VERY_VERBOSE
    esp32_ble: DEBUG
    esp32_ble_tracker: DEBUG
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    api: DEBUG
    api.service: DEBUG
```

**Comment by oguzatagan** [comment]
[logs_powerwall-bms_logs (1).txt](https://github.com/syssi/esphome-ant-bms/files/11235408/logs_powerwall-bms_logs.1.txt)

**Comment by syssi** [comment]
It is possible to retrieve to log via serial communication? I'm interested in some early messages. I'm looking for these lines:

```
[esp32_ble_client:064]: [0] [16:AA:22:02:23:45] 0x00 Attempting BLE connection
[esp32_ble_client:126]: [0] [16:AA:22:02:23:45] ESP_GATTC_OPEN_EVT
[esp32_ble_client:186]: [0] [16:AA:22:02:23:45] ESP_GATTC_SEARCH_CMPL_EVT
[esp32_ble_client:189]: [0] [16:AA:22:02:23:45] Service UUID: 0x1800
[esp32_ble_client:191]: [0] [16:AA:22:02:23:45]  start_handle: 0x1  end_handle: 0x9
[esp32_ble_client:189]: [0] [16:AA:22:02:23:45] Service UUID: 0x1801
[esp32_ble_client:191]: [0] [16:AA:22:02:23:45]  start_handle: 0xa  end_handle: 0xd
[esp32_ble_client:189]: [0] [16:AA:22:02:23:45] Service UUID: 0xFFE0
[esp32_ble_client:191]: [0] [16:AA:22:02:23:45]  start_handle: 0xe  end_handle: 0xffff
[esp32_ble_client:193]: [0] [16:AA:22:02:23:45] Connected
[esp32_ble_client:069]: [0] [16:AA:22:02:23:45]  characteristic 0xFFE1, handle 0x10, properties 0x1c
[esp32_ble_client:069]: [0] [16:AA:22:02:23:45]  characteristic 0xFFE2, handle 0x13, properties 0xc
```

They are missing at the last log capture.

**Comment by oguzatagan** [comment]
Of course I will add it soon.  thanks for your interest.

**Comment by oguzatagan** [comment]
[logs (1).txt](https://github.com/syssi/esphome-ant-bms/files/11235784/logs.1.txt)
here is my serial log

**Comment by syssi** [comment]
```
[I][esp32_ble_client:064]: [0] [AA:BB:CC:92:23:45] 0x00 Attempting BLE connection
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=40 gattc_if=4
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=2 gattc_if=4
[V][esp32_ble_client:129]: [0] [AA:BB:CC:92:23:45] ESP_GATTC_OPEN_EVT
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=46 gattc_if=4
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=7 gattc_if=4
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=7 gattc_if=4
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=7 gattc_if=4
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=6 gattc_if=4
[V][esp32_ble_client:189]: [0] [AA:BB:CC:92:23:45] ESP_GATTC_SEARCH_CMPL_EVT
[V][esp32_ble_client:192]: [0] [AA:BB:CC:92:23:45] Service UUID: 0x1800
[V][esp32_ble_client:194]: [0] [AA:BB:CC:92:23:45]  start_handle: 0x1  end_handle: 0x9
[V][esp32_ble_client:192]: [0] [AA:BB:CC:92:23:45] Service UUID: 0x1801
[V][esp32_ble_client:194]: [0] [AA:BB:CC:92:23:45]  start_handle: 0xa  end_handle: 0xd
[V][esp32_ble_client:192]: [0] [AA:BB:CC:92:23:45] Service UUID: 0xFFE0
[V][esp32_ble_client:194]: [0] [AA:BB:CC:92:23:45]  start_handle: 0xe  end_handle: 0xffff
[I][esp32_ble_client:196]: [0] [AA:BB:CC:92:23:45] Connected
[V][esp32_ble_client:069]: [0] [AA:BB:CC:92:23:45]  characteristic 0xFFE1, handle 0x10, properties 0x1c
[V][esp32_ble_client:069]: [0] [AA:BB:CC:92:23:45]  characteristic 0xFFE2, handle 0x13, properties 0xc
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=18 gattc_if=4
[V][esp32_ble_client:160]: [0] [AA:BB:CC:92:23:45] cfg_mtu status 0, mtu 136
[V][esp32_ble_client:114]: [0] [AA:BB:CC:92:23:45] gattc_event_handler: event=38 gattc_if=4
```

**Comment by oguzatagan** [comment]
will be?

**Comment by syssi** [comment]
I will ping you tomorrow as soon as I've prepared another test.

**Comment by oguzatagan** [comment]
thank you

**Comment by syssi** [comment]
I've pushed a change. Please update your ESP and provide another log!

**Comment by oguzatagan** [comment]
[logs_powerwall-bms_run.txt](https://github.com/syssi/esphome-ant-bms/files/11240849/logs_powerwall-bms_run.txt)
[logs (2).txt](https://github.com/syssi/esphome-ant-bms/files/11240850/logs.2.txt)

sorry sir im late because im sick. one of the serial other one is wirelessly

**Comment by syssi** [comment]
Good news! The BMS did respond this time probably with a valid status frame!

**Comment by oguzatagan** [comment]
So is there hope? =)

**Comment by syssi** [comment]
Yes!

**Comment by syssi** [comment]
Could you provide a photo of the BMS model sticker?

**Comment by oguzatagan** [comment]
you re perfect! 
![IMG_20230416_103040](https://user-images.githubusercontent.com/34588356/232280872-c590b9fe-51c7-4e8b-b9a2-b0f7470443ad.jpg)

**Comment by syssi** [comment]
Hmm... does the Android app provide any details about the BMS model?

**Comment by oguzatagan** [comment]
There is a "ble avl" button on the top left.  It counts down when I press it.  but I don't know what it does.  there is also the rv: number in the upper left.  I'll be home in an hour, I'll take a closer look

**Comment by syssi** [comment]
The device support is ready. Please give it a try using this YAML:

https://github.com/syssi/esphome-ant-bms/blob/old-proto-ble/esp32-old-ble-example.yaml

**Comment by oguzatagan** [comment]
you are perfect. There is a small detail, the password must be 12345678. It shows only data, closed to editing and command retrieval. Since I have never used this password with rfcomm, I told you the bluetooth pair password. I tried to change the yaml file but it gives the error I added.
![Ekran Alıntısı](https://user-images.githubusercontent.com/34588356/232306712-31843cf2-cb89-4df4-818f-5aedba50c6be.PNG)

**Comment by syssi** [comment]
I've pushed a fix. Please give it another try!

**Comment by oguzatagan** [comment]
this time compiled and installed.  but again it doesn't allow change.  It beeps 3 times bms.  I can give the following in details.  In the past, I did not enter any password to make changes in the android application.  now when esp 32 is connected, then when esp32 is closed and connected with android application, I cannot make changes without typing 12345678 password.  When I type 12345678 and confirm, it allows change.  I am sharing the screenshot of the app.  in the application there are flashbacks when I type and confirm the password.
![Uploading Screenshot_20230416_162926_com.lecheng.hello.ant_bms.jpg…]()

**Comment by oguzatagan** [comment]
![Screenshot_20230416_162926_com lecheng hello ant_bms](https://user-images.githubusercontent.com/34588356/232315594-85a4a853-2b1a-4653-830b-478679607613.jpg)

**Comment by syssi** [comment]
Do see the BMS beep too if you enter the password using the app? Does the BMS beep if you enter a wrong password? I would like to understand the three beeps.

**Comment by oguzatagan** [comment]
yes, when I enter the password 12345678 in the android application, a single beep sounds and allows the change.  3 beeps occur when I enter a different password.

**Comment by syssi** [comment]
Could you try to capture the bluetooth traffic using this method: https://medium.com/@charlie.d.anderson/how-to-get-the-bluetooth-host-controller-interface-logs-from-a-modern-android-phone-d23bde00b9fa

And could you provide another ESPHome log with loglevel `VERY_VERBOSE` enabled + try to change some settings. I want to see the different `Send command: ...` messages.

**Comment by syssi** [comment]
Could you try to control your BMS using an empty password too?

```
ant_bms_old_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 5s
    password: ""
```

**Comment by syssi** [comment]
In best case I've found the root cause. I've pushed a fix. Please flash your ESP again and give it another try!

**Comment by oguzatagan** [comment]
home assistant crashed =) and I'm not at home.  I'll be home in 3 hours, I'll try.  Thank you for your patience

**Comment by oguzatagan** [comment]
still no change.  It does not accept commands.  i will try to capture the commands at home

**Comment by syssi** [comment]
Could you check it's still beeping three times (if you are at home)?

**Comment by oguzatagan** [comment]
> Could you check it's still beeping three times (if you are at home)?

I'm not at home, but I gave a remote command and made my brother listen to the sound.  It still comes 3 times.

**Comment by oguzatagan** [comment]
While compiling it is updating on the old yaml file.  Do you think deleting the old build file and reinstalling it will work or is it unnecessary?

**Comment by syssi** [comment]
There is a "clean build" button at the ESPHome dashboard.

**Comment by oguzatagan** [comment]
i compiled but it doesnt work. i will try capture

**Comment by syssi** [comment]
Could you provide another VERY_VERBOSE log?

**Comment by oguzatagan** [comment]
[logs_powerwall-bms_logs (2).txt](https://github.com/syssi/esphome-ant-bms/files/11243811/logs_powerwall-bms_logs.2.txt)

**Comment by oguzatagan** [comment]
I got an idea. Once I enter a password in the Android application, when I close the program and open it again, it allows the change without asking for the password again. We have a chance to change esp32's mac address with android mac address with esphome?

**Comment by oguzatagan** [comment]
Bluetooth Hcidump [<=Jelly Bean]

Bluetooth Bluedroid Harici Ayrıştırıcı [Kitkat]

Bluetooth BtsnoopNet [>=Lollipop]

which one is true for capture. my phone have a 9 pie

**Comment by syssi** [comment]
The mentioned article above should work for your Android 9 device. I try to summarize the process:

1. Enable the developer options
2. Enable HCI Bluetooth Snooping at the developer options
3. Turn off bluetooth + turn on bluetooth
4. Open the BMS app
5. Send the password
6. Toggle some MOSFET switches
7. Close the app
8. Use "adb" to retrieve a `bugreport`
9. Extract the ZIP bundle and look at the mentioned folder for the *btsnoop*.log*.

**Comment by syssi** [comment]
The last ESPHome log doesn't contain any Mosfet switch changes.  Could you provide another log containing some changes of the switch states?

Could you do another test and provide the log of controlling the BMS without a password:

```
ant_bms_old_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 5s
    password: ""
```

**Comment by oguzatagan** [comment]
> The mentioned article above should work for your Android 9 device. I try to summarize the process:
> 
> 1. Enable the developer options
> 2. Enable HCI Bluetooth Snooping at the developer options
> 3. Turn off bluetooth + turn on bluetooth
> 4. Open the BMS app
> 5. Send the password
> 6. Toggle some MOSFET switches
> 7. Close the app
> 8. Use "adb" to retrieve a `bugreport`
> 9. Extract the ZIP bundle and look at the mentioned folder for the _btsnoop_.log*.

Unfortunately, on my mate 9 android 9 phone, the btsnoop file does not come out of the debug file. If I find another old version android device, I will try with it.

**Comment by oguzatagan** [comment]
without password  `Password: ""
`
[logs_powerwall-bms_run (2).txt](https://github.com/syssi/esphome-ant-bms/files/11256739/logs_powerwall-bms_run.2.txt)

```
'switch:017]: 'powerwall-bms charging' Turning OFF.
[03:12:30][I][ant_bms_old_ble:469]: Authentication skipped because there was no password provided'
```

with password `Password: "12345678"`


[logs_powerwall-bms_run (3).txt](https://github.com/syssi/esphome-ant-bms/files/11256798/logs_powerwall-bms_run.3.txt)

```
[switch:017]: 'powerwall-bms charging' Turning OFF.
[03:26:28][D][ant_bms_old_ble:473]: Authenticate write command
```
But 2 options have 3 beeps. İ think Authenticated is correct but send command is false or another. Because Android app with 12345678 password have a 1 beep but esp32 send command with or without password always 3 beeps.

**Comment by oguzatagan** [comment]
hello again. finally got it with xiaomi. I am attaching it to you.
[btsnoop_hci.log](https://github.com/syssi/esphome-ant-bms/files/11278019/btsnoop_hci.log)

**Comment by syssi** [comment]
Good job! I've extracted the authentication traffic:

```
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:38:63
WRITE a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f4:37:38:63
```

```
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:39:64
5a:5a:ff:00:00:ff
5a:5a:ff:00:00:ff
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f5:00:01:f6
```

```
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:38:63
WRITE a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f4:37:38:63
```

All write commands of the capture:

```
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:f5:00:01:f6
WRITE a5:a5:f9:00:01:fa
WRITE a5:a5:f5:00:01:f6
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:38:63
WRITE a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f4:37:38:63
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:f9:00:01:fa
WRITE a5:a5:f9:00:01:fa
WRITE a5:a5:fa:00:00:fa
WRITE a5:a5:fa:00:00:fa
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:39:64
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f5:00:01:f6
WRITE a5:a5:f1:31:32:54:a5:a5:f2:33:34:59:a5:a5:f3:35:36:5e:a5:a5:f4:37:38:63
WRITE a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f5:00:01:f6:a5:a5:f4:37:38:63
WRITE a5:a5:fa:00:01:fb
WRITE a5:a5:fa:00:01:fb
```

I have not yet had time to compare the frames with the implementation.

**Comment by syssi** [comment]
I've identified a difference and pushed a fix. Could you update your ESP, try again (with `password: "12345678"`) and provide another log?

**Comment by oguzatagan** [comment]
you r a genius. Now send command 1 beep and working
[logs_powerwall-bms_logs (4).txt](https://github.com/syssi/esphome-ant-bms/files/11288474/logs_powerwall-bms_logs.4.txt)

**Comment by syssi** [comment]
Awesome! Please test all controls. Do you miss something or does something doesn't work as expected? If everything is fine the device support is ready to merge.

**Comment by oguzatagan** [comment]
thanks for everthink. you can merge  2 questions?

1-Can we see cell difference value?
2-can we see system log in home assistant?

**Comment by oguzatagan** [comment]
and i have deye inverter. it is support modbus. Can we comminicate inverter and bms with esphome?

**Comment by syssi** [comment]
1. Cell difference: I will gave a look.
2. Do you mean the log of the BMS or the ESPHome node in general?
3. Which Deye inverter do you own?

**Comment by oguzatagan** [comment]
1. thanks
2. bms internally logs. It's not a big important, but it would be nice if it did.
3. deye hybrid sun-5k-sg01lp1

**Comment by oguzatagan** [comment]
I gave you a headache. sorry. I need help. I tried to create both bms and heltec balancer in the same esp32, but bms is connecting but heltec balancer is not connecting, where am I wrong? can you help me? 

`substitutions:
  name: powerwall-bms
  name1: Heltec
  external_components_source1: github://syssi/esphome-ant-bms@old-proto-ble
  external_components_source2: github://syssi/esphome-jk-bms@main
  mac_address1: aa:bb:cc:92:23:45
  mac_address2: 3c:a5:51:89:35:ec

esphome:
  name: powerwall-bms
  platform: ESP32
  board: esp32dev
  platformio_options: 
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L
  project:
    name: "syssi.esphome-ant-bms"
    version: 2.0.0

external_components:
  - source: ${external_components_source1}
    refresh: 0s
  - source: ${external_components_source2}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: ""

logger:
  level: DEBUG

api:
  encryption:
    key: 

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("ANT-", 0) == 0) {
            ESP_LOGI("ble_adv", "New ANT-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

      - lambda: |-
          if (x.get_name().rfind("GW-", 0) == 0) {
            ESP_LOGI("ble_adv", "New Heltec/NEEY balancer found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - id: client1
    mac_address: ${mac_address1}
  - id: client2
    mac_address: ${mac_address2}

ant_bms_old_ble:
  - id: bms1
    ble_client_id: client1
    update_interval: 5s
    password: "12345678"

heltec_balancer_ble:
  - ble_client_id: client2
    throttle: 5s
    id: bms2

binary_sensor:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    online_status:
      name: "ant bms online status"
  - platform: heltec_balancer_ble
    balancing:
      name: "${name1} balancing"
    online_status:
      name: "${name1} online status"

sensor:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    battery_strings:
      name: "${name} battery strings"
    current:
      name: "${name} current"
    soc:
      name: "${name} soc"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    capacity_remaining:
      name: "${name} capacity remaining"
    battery_cycle_capacity:
      name: "${name} battery cycle capacity"
    total_voltage:
      name: "${name} total voltage"
    total_runtime:
      name: "${name} total runtime"
    power:
      name: "${name} power"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    temperature_5:
      name: "${name} temperature 5"
    temperature_6:
      name: "${name} temperature 6"
    
    
    charge_mosfet_status_code:
      name: "${name} charge mosfet status code"
    discharge_mosfet_status_code:
      name: "${name} discharge mosfet status code"
    balancer_status_code:
      name: "${name} balancer status code"

  - platform: heltec_balancer_ble
    min_cell_voltage:
      name: "${name1} min cell voltage"
    max_cell_voltage:
      name: "${name1} max cell voltage"
    min_voltage_cell:
      name: "${name1} min voltage cell"
    max_voltage_cell:
      name: "${name1} max voltage cell"
    delta_cell_voltage:
      name: "${name1} delta cell voltage"
    average_cell_voltage:
      name: "${name1} average cell voltage"
    cell_voltage_1:
      name: "${name1} cell voltage 1"
    cell_voltage_2:
      name: "${name1} cell voltage 2"
    cell_voltage_3:
      name: "${name1} cell voltage 3"
    cell_voltage_4:
      name: "${name1} cell voltage 4"
    cell_voltage_5:
      name: "${name1} cell voltage 5"
    cell_voltage_6:
      name: "${name1} cell voltage 6"
    cell_voltage_7:
      name: "${name1} cell voltage 7"
    cell_voltage_8:
      name: "${name1} cell voltage 8"
    cell_voltage_9:
      name: "${name1} cell voltage 9"
    cell_voltage_10:
      name: "${name1} cell voltage 10"
    cell_voltage_11:
      name: "${name1} cell voltage 11"
    cell_voltage_12:
      name: "${name1} cell voltage 12"
    cell_voltage_13:
      name: "${name1} cell voltage 13"
    cell_voltage_14:
      name: "${name1} cell voltage 14"
    total_voltage:
      name: "${name1} total voltage"
    temperature_sensor_1:
      name: "${name1} temperature sensor 1"
    temperature_sensor_2:
      name: "${name1} temperature sensor 2"
    total_runtime:
      name: "${name1} total runtime"
    balancing_current:
      name: "${name1} balancing current"
    # Not implemented
    # errors_bitmask:
    #   name: "${name} errors bitmask"
    cell_detection_failed_bitmask:
      name: "${name1} cell detection failed bitmask"
    cell_overvoltage_bitmask:
      name: "${name1} cell overvoltage bitmask"
    cell_undervoltage_bitmask:
      name: "${name1} cell undervoltage bitmask"
    cell_polarity_error_bitmask:
      name: "${name1} cell polarity error bitmask"
    cell_excessive_line_resistance_bitmask:
      name: "${name1} cell excessive line resistance bitmask"

text_sensor:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    charge_mosfet_status:
      name: "${name} charge mosfet status"
    discharge_mosfet_status:
      name: "${name} discharge mosfet status"
    balancer_status:
      name: "${name} balancer status"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
  - platform: heltec_balancer_ble
    # Not implemented
    # errors:
    #   name: "${name} errors"
    operation_status:
      name: "${name1} operation status"
    total_runtime_formatted:
      name: "${name1} total runtime formatted"
    buzzer_mode:
      name: "${name1} buzzer mode"
    battery_type:
      name: "${name1} battery type"

switch:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
  - platform: heltec_balancer_ble
    balancer:
      name: "${name1} balancer"

button:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    shutdown:
      name: "${name} shutdown"
    clear_counter:
      name: "${name} clear counter"
    balancer:
      name: "${name} balancer"
    factory_reset:
      name: "${name} factory reset"
    restart:
      name: "${name} restart"
  - platform: heltec_balancer_ble
    retrieve_settings:
      name: "${name1} retrieve settings"
      id: retrieve_settings_button
    retrieve_device_info:
      name: "${name1} retrieve device info"
    retrieve_factory_defaults:
      name: "${name1} retrieve factory defaults"

number:
  - platform: heltec_balancer_ble
    cell_count:
      name: "${name1} cell count"
    balance_trigger_voltage:
      name: "${name1} balance trigger voltage"
    max_balance_current:
      name: "${name1} max balance current"
    balance_sleep_voltage:
      name: "${name1} balance sleep voltage"
    balance_start_voltage:
      name: "${name1} balance start voltage"
    nominal_battery_capacity:
      name: "${name1} nominal battery capacity"

interval:
  - interval: 30min
    then:
      - button.press: retrieve_settings_button`

**Comment by syssi** [comment]
Your configuration looks good in general. If you reduce the YAML again to talk to the balancer only does it work in this case?

**Comment by oguzatagan** [comment]
> Your configuration looks good in general. If you reduce the YAML again to talk to the balancer only does it work in this case?

yes. only heltec ble yaml is good working. when i merge bms is online but heltec is disconnected

**Comment by syssi** [comment]
Could you try to assign the heltec entities to a selected heltec instance?

```
heltec_balancer_ble:
  - ble_client_id: client2
    throttle: 5s
    id: bms2

switch:
  - platform: ant_bms_old_ble
    ant_bms_old_ble_id: bms1
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
  - platform: heltec_balancer_ble
    heltec_balancer_ble_id: bms2
    balancer:
      name: "${name1} balancer"

sensor:
# ....
  - platform: heltec_balancer_ble
    heltec_balancer_ble_id: bms2
    min_cell_voltage:
      name: "${name1} min cell voltage"
    max_cell_voltage:
      name: "${name1} max cell voltage"

**Comment by syssi** [comment]
Please try this ESPHome based solution for your Deye inverter: https://github.com/klatremis/esphome-for-deye

**Comment by oguzatagan** [comment]
> logger:
>   level: VERY_VERBOSE
>   logs:
>     ant_bms_ble: VERY_VERBOSE
>     ble_client: VERY_VERBOSE
>     esp32_ble: DEBUG
>     esp32_ble_tracker: DEBUG
>     scheduler: DEBUG
>     component: DEBUG
>     sensor: DEBUG
>     api: DEBUG
>     api.service: DEBUG

[logs_powerwall-bms_run (1).txt](https://github.com/syssi/esphome-ant-bms/files/11299910/logs_powerwall-bms_run.1.txt) 

Unfortunately it didn't connect that way either. I sent the log, can you review it?

**Comment by syssi** [comment]
Please update the `esp32` section and use the `esp-idf` framework instead of the default (Arduino):

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
```

**Comment by oguzatagan** [comment]
> Please update the `esp32` section and use the `esp-idf` framework instead of the default (Arduino):
> 
> ```
> esp32:
>   board: wemos_d1_mini32
>   framework:
>     type: esp-idf
> ```

you are perfect. Now 2 nodes working.

**Comment by syssi** [comment]
Let's declare this issue as resolved. Please create new issues if you miss some ANT-BMS feature or if you see room for improvements. Please create an issue here if you need support by integrating other devices into ESPHome: https://github.com/syssi/esphome-config-examples
